project:
  type: website

website:
  title: "Capivara"
navbar:
  background: "#6b1d6b"
  foreground: white
  left:
    - text: Overview
      href: "#overview"
    - text: Installation
      href: "#installation"
    - text: Usage
      href: "#usage"
    - text: Reference
      href: "#references"
  right:
    - icon: github
      href: https://github.com/RafaelSdeSouza/capivara

  page-footer:
    left: "© 2026 Rafael S. de Souza"
    right: "Built with Quarto"

format:
  html:
    theme:
      light: flatly
    toc: true
    toc-location: body
    toc-depth: 3
    code-copy: true
    code-line-numbers: true
    smooth-scroll: true
    css: styles.css
