# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

capivara_hgc_snn_cut_cpp <- function(nn_idx, target_k) {
    .Call('_capivara_capivara_hgc_snn_cut_cpp', PACKAGE = 'capivara', nn_idx, target_k)
}

