# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

capivara_observed_ward_cpp <- function(features, validity, edges, original_ids, feature_group, min_shared_fraction, min_contributor_fraction, min_feature_fraction, input_error_gamma, leaf_signatures, target_k) {
    .Call(`_capivara_capivara_observed_ward_cpp`, features, validity, edges, original_ids, feature_group, min_shared_fraction, min_contributor_fraction, min_feature_fraction, input_error_gamma, leaf_signatures, target_k)
}

capivara_sparse_ward_cut_cpp <- function(features, nn_idx, target_k) {
    .Call(`_capivara_capivara_sparse_ward_cut_cpp`, features, nn_idx, target_k)
}

